
name: Request Icon
description: An issue to request an icon
title: "[Icon]: "
labels: ["enhancement", "request icon"]
assignees:
  - Gustavy
  - Daniel-Dukundane
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this icon request report!"
  - type: textarea
    id: what-icon-do-you-request
